build:
  - "Makefile"
  - "pyproject.toml"
  - "**/tsconfig.*"
  - "tsconfig.*"
ci:
  - ".github/workflows/*"
deps:
  - "go.mod"
  - "go.sum"
  - "package.json"
  - "package-lock.json"
  - "poetry.lock"
  - "renovate.json"
  - "requirements.txt"
deployment:
  - ".dockerignore"
  - "Containerfile"
  - "Dockerfile"
docs:
  - "CODEOWNERS"
  - "*.md"
  - "**/*.md"
json:
  - "*.json"
  - "**/*.json"
shell:
  - "*.sh"
  - "**/*.sh"
style:
  - ".eslintignore"
  - ".eslintrc.js"
  - ".prettierignore"
  - ".prettierrc.json"
  - ".pre-commit-config.yaml"
  - ".pre-commit-hook.sh"
test:
  - "**/*.spec.js"
  - "**/*.spec.ts"
  - "**/*.test.js"
  - "**/*.test.ts"
  - "**/__test__/*"
  - "**/__test__/**/*"
  - "**/test_*.py"
  - "**/tests/*"
  - "**/tests/**/*"
yaml:
  - "*.yaml"
  - "*.yml"
  - "**/*.yaml"
  - "**/*.yml"
