name: yaml
on:
  push:
    branches:
      - $default-branch
    paths:
      - "**.yml"
      - "**.yaml"
  pull_request:
    paths:
      - "**.yml"
      - "**.yaml"
  workflow_dispatch:
jobs:
  lint:
    uses: darioblanco/.github/.github/workflows/yaml.yaml@v1
