name: Reusable Container
on:
  workflow_call:
    inputs:
      contextPath:
        required: false
        description: The container context to build the image
        default: .
        type: string
      extraBuildArgs:
        required: false
        description: Extra build arguments for building the docker image (KEY=VALUE separated by new lines)
        default: ""
        type: string
      filePath:
        required: false
        description: The file path for the Container image
        default: Containerfile
        type: string
      name:
        required: true
        description: The container image name
        type: string
      platforms:
        required: false
        description: The target platforms the image will be built into
        default: linux/amd64,linux/arm64
        type: string
      registryHostname:
        required: false
        description: The hostname for the container registry
        default: ghcr.io
        type: string
      registryOrg:
        required: false
        description: The registry organization
        default: darioblanco
        type: string
      registryUsername:
        required: false
        description: The username for the container registry
        default: darioblanco
        type: string
      runner:
        required: false
        description: Runner type
        default: ubuntu-latest
        type: string
      version:
        required: false
        description: The specific version to push (will be added to the automated ones)
        default: ""
        type: string
    secrets:
      registryPassword:
        required: true
        description: The password for the container registry
jobs:
  container:
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Checkout current git repository
        uses: actions/checkout@v3
      - name: Prepare
        id: prep
        run: |
          BRANCH=${GITHUB_REF##*/}
          TS=$(date +%s)
          REVISION=${GITHUB_SHA::8}
          BUILD_ID="${BRANCH}-${REVISION}-${TS}"
          LATEST_ID=canary
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            BUILD_ID=${GITHUB_REF/refs\/tags\//}
            LATEST_ID=latest
          fi
          if [[ "${{ inputs.version }}" != "" ]]; then
            LATEST_ID=${{ inputs.version }}
          fi
          {
            echo build_date="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            echo build_id="${BUILD_ID}"
            echo latest_id="${LATEST_ID}"
           } >> "$GITHUB_OUTPUT"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registryHostname }}
          username: ${{ inputs.registryUsername }}
          password: ${{ secrets.registryPassword }}
      - name: Build and push latest version
        uses: docker/build-push-action@v5
        id: docker_build
        with:
          build-args: |
            GITHUB_SHA=${{ github.sha }}
            VERSION=${{ inputs.version }}
            ${{ inputs.extraBuildArgs }}
          cache-from: type=registry,ref=${{ inputs.registryHostname }}/${{ inputs.registryOrg }}/${{ inputs.name }}
          cache-to: type=inline
          context: ${{ inputs.contextPath }}
          file: ${{ inputs.filePath }}
          platforms: ${{ inputs.platforms }}
          push: true
          tags: |
            ${{ inputs.registryHostname }}/${{ inputs.registryOrg }}/${{ inputs.name }}:${{ github.sha }}
            ${{ inputs.registryHostname }}/${{ inputs.registryOrg }}/${{ inputs.name }}:${{ steps.prep.outputs.build_id }}
            ${{ inputs.registryHostname }}/${{ inputs.registryOrg }}/${{ inputs.name }}:${{ steps.prep.outputs.latest_id }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
