name: Reusable Python
on:
  workflow_call:
    inputs:
      pythonVersion:
        required: false
        description: The python version to provide (e.g. `3.x`)
        default: 3.x
        type: string
      runner:
        required: false
        description: Runner type
        default: ubuntu-latest
        type: string
jobs:
  python:
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Checkout current git repository
        uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.pythonVersion }}
      - name: Install requirements
        run: make install
      - name: Validate code style
        run: make lint
      - name: Test code
        run: make test
